analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 1
title: VERKSTEDET ORGANISATION
cta:
  bucket: null
  version: null
  domain: null
color:
  saturation: 0.5
  brandStrength: 0
  rhythmicContrast: 0.3465830634813756
  brandColors:
    - '#c3dc96'
    - '#555555'
    - '#000000'
    - '#72883c'
    - '#ffff00'
  lightness: 0.9663184199016541
purpose: []
favicon: null
name: verkstedet.org
typography_spectrum: 1
