name: VERKSTEDET.ORG
favicon: null
layout_spectrum: 0.49076
typography_spectrum: 0.59898
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: THE VERKSTEDET ORGANIZATION
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-72303773-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#a4b97e'
    - '#515151'
    - '#b03425'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
