name: verkstedet.org
favicon: null
layout_spectrum: 1
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c3dc96'
    - '#555555'
    - '#000000'
    - '#72883c'
    - '#ffff00'
  brandStrength: 0
  lightness: 0.9663184199016541
  saturation: 0.5
  rhythmicContrast: 0.3465830634813756
purpose: []
